%-------------------------------------------------------------
% plik menu Warianty i kryteria
%-------------------------------------------------------------
% Hubert Gawryœ   2014-03-16
% Instytut Zarz¹dzania w Budownictwie i Transporcie (L-3)
% Wydzia³ In¿ynierii L¹dowej
% Politechnika Krakowska im. Tadeusza Koœciuszki
%-------------------------------------------------------------
% Xij        - macierz ocen wariantów dla kryteriów
% SD         - wektor charakteru kryteriów
% Vij        - wektor wag kryteriów
%-------------------------------------------------------------
clear_fig(1,lmenu);

wysokoscrzedu1=200;
wysokoscrzedu2=530;
wysokoscrzedu3=80;
Pos2=get(fig,'Position');
nr_alert=1;
All_alert;
%-------------------------------------------------------------
%-------------------------------------------------------------

[N,M]=size(Xij);
if N<w411
    
    for i=(N+1):w411
        Xij(i,:)=0;
    end
elseif N>w411
    for i=(w411+1):N
        Xij(w411+1,:)=[];
    end
end
if M<w511
    for i=(M+1):w511
        Xij(:,i)=0;
        SD(1,i)=1;
        Vij(1,i)=1;
    end
elseif M>w511
    for i=(w511+1):M
        Xij(:,w511+1)=[];
        SD(:,w511+1)=[];
        Vij(:,w511+1)=[];
    end
end
%-------------------------------------------------------------
w41=uicontrol(gcf,'style','edit',...
    'FontSize',8,...
    'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),...
    'String',w411,...
    'Position',[100 wysokoscrzedu2 50 20],...
    'Callback','wczytaj_dane2; l_dane');

w51=uicontrol(gcf,'style','edit',...
    'FontSize',8,...
    'FontWeight','bold',...
    'BackGroundColor',kol2(6,:),...
    'String',w511,...
    'Position',[200 wysokoscrzedu2 50 20],...
    'Callback','wczytaj_dane3; l_dane');

%-------------------------------------------------------------
w15=uicontrol(gcf,'style','text',...
    'FontSize',8,...
    'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),...
    'String','W',...
    'Position',[70 wysokoscrzedu2 15 20]);

w16=uicontrol(gcf,'style','text',...
    'FontSize',8,...
    'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),...
    'String','K',...
    'Position',[170 wysokoscrzedu2 15 20]);

w17=uicontrol(gcf,'style','text',...
    'FontSize',8,...
    'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),...
    'String','WprowadŸ oceny dla wariantów (Wi- i-ty wariant, Kj- j-te kryterium)',...
    'Position',[50 wysokoscrzedu2-30 420 20]);

w18=uicontrol(gcf,'style','text',...
    'FontSize',8,...
    'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),...
    'String','Podaj charakter kryterium (1-stymulanta, 2-destymulanta)',...
    'Position',[50 210 370 20]);

w19=uicontrol(gcf,'style','text',...
    'FontSize',8,...
    'FontWeight','bold',...
    'BackGroundColor',kol2(5,:),...
    'String','Podaj wagi dla poszczególnych kryteriów',...
    'Position',[50 130 280 20]);

%-------------------------------------------------------------
w1=uitable(gcf,'ColumnName',KKK(1:w511),...
    'RowName',WWW(1:w411),...
    'ColumnEditable',true,...
    'CellEditCallback','wczytaj_dane4',...
    'Data',Xij,...
    'Position',[70 240 450 260]);
set(w1,'ColumnWidth',{30})

w2=uitable(gcf,'ColumnName',KKK(1:w511),...
    'ColumnEditable',true,...
    'CellEditCallback', 'wczytaj_dane5; nr_alert=2; All_alert; l_dane',...
    'Data',SD,...
    'RowName','SD',...
    'Position',[70 160 450 50]);
set(w2,'ColumnWidth',{30})

w3=uitable(gcf,'ColumnName',KKK(1:w511),...
    'ColumnEditable',true,...
    'CellEditCallback','wczytaj_dane6',...
    'Data',Vij,...
    'RowName','Vj',...
    'Position',[70 80 450 50]);
set(w3,'ColumnWidth',{30})
%-------------------------------------------------------------

hp11=uipanel('Title','Dane wejœciowe','FontSize',8,...
    'BackgroundColor',kol2(5,:),'ForeGroundColor','b',...
    'Position',[ 40/wymiarx 40/wymiary 560/wymiarx 540/wymiary]);
